# Generated by Django 3.0.3 on 2020-04-23 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_apps', '0007_auto_20200403_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='cmt_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 16, 3, 39, 740771)),
        ),
    ]
